// Regenerates src/emojidata.ts from Unicode's emoji-test.txt (UTS #51).
//   node scripts/gen-emoji.mjs [path-to-emoji-test.txt]
// Downloads the latest file when no path is given. Skin-tone and hair variants are dropped:
// they multiply the list five-fold for one name, and the panel's field still takes any of them.
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "https://unicode.org/Public/emoji/latest/emoji-test.txt";

const text = process.argv[2]
  ? readFileSync(process.argv[2], "utf8")
  : await (await fetch(SRC)).text();

let version = "", group = "";
const groups = [];
for (const line of text.split("\n")) {
  const v = /^# Version: (\S+)/.exec(line);
  if (v) version = v[1];
  const g = /^# group: (.+)$/.exec(line);
  if (g) { group = g[1].trim(); continue; }
  if (group === "Component" || !/; fully-qualified/.test(line)) continue;
  // `1F600 ; fully-qualified # 😀 E1.0 grinning face`
  const m = /#\s(\S+)\sE(\d+\.\d+)\s(.+)$/.exec(line);
  if (!m || /skin tone/.test(m[3])) continue;
  if (groups.at(-1)?.name !== group) groups.push({ name: group, items: [] });
  groups.at(-1).items.push(`${m[1]} ${m[3].trim()}`);
}

const all = groups.flatMap((g) => g.items);
const starts = [];
let n = 0;
for (const g of groups) { starts.push([g.name, n]); n += g.items.length; }

const out = `// GENERATED by scripts/gen-emoji.mjs from Unicode emoji-test.txt ${version}. Do not edit.
// One entry per emoji, "<char> <name>", ordered by group; EMOJI_GROUPS says where each starts.
export const EMOJI_GROUPS: readonly (readonly [string, number])[] = ${JSON.stringify(starts)};

export const EMOJI_ALL: readonly string[] = ${JSON.stringify(all, null, 0).replace(/","/g, '",\n  "').replace(/^\[/, "[\n  ").replace(/\]$/, ",\n]")};
`;
writeFileSync(new URL("../src/emojidata.ts", import.meta.url), out);
console.log(`${all.length} emoji, ${groups.length} groups, Unicode ${version}`);
