// The conversation outline: the prompts you sent, listed as anchors back into the pane's
// scrollback. Rules only — ./terminal owns the anchors and ./inspectorview draws the rows.
// In memory only, like a tool payload: a prompt is conversation and never reaches storage.

import type { Prompt } from "./types";

export interface OutlinePrefs {
  enabled: boolean;
  // Rendered lines a folded row shows. The fold is CSS line-clamp, so a wrapped one-liner
  // and a five-line prompt cost the same height, which is what the rail's width needs.
  lines: number;
  hover: boolean; // resting on a row unfolds it
}

export const OUTLINE_DEFAULTS: OutlinePrefs = { enabled: true, lines: 3, hover: true };
export const OUTLINE_LINES = [1, 2, 3, 5];
export const OUTLINE_SHOW = 6; // rows before the list folds; the rest are one click away

export function clampOutlinePrefs(p: Partial<OutlinePrefs> | null | undefined): OutlinePrefs {
  const lines = Number(p?.lines);
  return {
    enabled: p?.enabled !== false,
    lines: OUTLINE_LINES.includes(lines) ? lines : OUTLINE_DEFAULTS.lines,
    hover: p?.hover !== false,
  };
}

// A memory bound, not a display one: a pane's scrollback runs out long before this, and a
// row whose anchor has gone is still worth reading.
export const PROMPT_CAP = 200;
const TEXT_CAP = 4000; // as ./toolio caps a payload, and for the same reason

export function cleanPrompt(raw: unknown): string {
  if (typeof raw !== "string") return "";
  const t = raw.replace(/\r\n?/g, "\n").replace(/[ \t]+$/gm, "").replace(/\n{3,}/g, "\n\n").trim();
  return t.length > TEXT_CAP ? t.slice(0, TEXT_CAP) + "…" : t;
}

/** The single line a tooltip or a folded row falls back to. */
export function promptLabel(text: string): string {
  const first = text.split("\n").find((l) => l.trim()) ?? "";
  return first.length > 120 ? first.slice(0, 120) + "…" : first;
}

// Turns Claude submits as `user` that nobody typed: a slash command's echo, a `!` shell line,
// an image's sidecar, the notification a background task finished. `UserPromptSubmit` fires for
// these as if you had pressed Enter, so both paths drop them — and only at the START of a
// message, since a `<system-reminder>` pasted INTO a real question leaves it a real question.
const ENVELOPES = [
  "<command-name>", "<command-message>", "<command-args>", "<local-command-stdout>",
  "<local-command-caveat>", "<system-reminder>", "<task-notification>",
  "<bash-input>", "<bash-stdout>", "<bash-stderr>",
  "Caveat: The messages below were generated by the user", "[Request interrupted by user",
  "[Image: ", // what a pasted image files beside the question; `[Image #1] …` IS the question
];
export const isEnvelope = (text: string): boolean => ENVELOPES.some((e) => text.startsWith(e));

let seq = 0;
// Guards a resend of one submit (Codex reports a message twice, started and completed),
// never asking the same thing twice on purpose: a repeat a turn later is its own entry.
const REPEAT_MS = 1500;

/** Returns the entry so the caller can anchor it; null when there is nothing to list. */
export function notePrompt(list: Prompt[], raw: unknown, now: number): Prompt | null {
  const text = cleanPrompt(raw);
  if (!text || isEnvelope(text)) return null;
  const last = list[list.length - 1];
  if (last && last.text === text && now - last.at < REPEAT_MS) return null;
  const p: Prompt = { id: `p${++seq}`, text, at: now };
  list.push(p);
  if (list.length > PROMPT_CAP) list.splice(0, list.length - PROMPT_CAP);
  return p;
}

// SessionStart fires for all four; only `clear` starts an empty conversation on a cleared
// screen. /compact and /resume carry on, and their prompts are still up in the scrollback.
export const clearsOutline = (source: unknown): boolean => String(source ?? "") === "clear";

// ---------- a resumed pane: the questions are in the transcript, not in its hooks ----------

/** One provider history message, as ./providers hands it over. */
export interface SeedMsg { role: string; text: string; at?: string | null }

/**
 * Everything the transcript holds predates this pane, so restored entries go in front of
 * whatever it has already recorded. Runs once: a second read would list the lot twice, and
 * no dedupe can tell that from a question genuinely asked twice.
 */
export function seedPrompts(list: Prompt[], msgs: readonly SeedMsg[]): Prompt[] {
  if (list.some((p) => p.restored)) return [];
  const restored: Prompt[] = [];
  for (const m of msgs) {
    if (m.role !== "user") continue;
    const text = cleanPrompt(m.text);
    if (!text || isEnvelope(text)) continue;
    const at = m.at ? Date.parse(m.at) : NaN;
    restored.push({ id: `p${++seq}`, text, at: Number.isFinite(at) ? at : 0, restored: true });
  }
  list.unshift(...restored);
  if (list.length > PROMPT_CAP) list.splice(0, list.length - PROMPT_CAP);
  return restored;
}

// ---------- finding a question in a pane's scrollback ----------
// The address is the text, not a coordinate: the submit hook fires when you press Enter, and
// the REPL commits the line afterwards, above where the cursor then was (docs/sessions.md).

/** A terminal row, read as prose: the REPL's own `>` marker is not part of the question. */
export const normLine = (raw: string): string =>
  raw.replace(/\s+/g, " ").replace(/^[\s>│┃|]+/, "").trim();

export interface PromptKey { key: string; strict: boolean }
const KEY_MAX = 60; // enough to be this question rather than a similar one
const KEY_SHORT = 24; // the retry, for a REPL that wrapped the message narrower than KEY_MAX
const KEY_MIN = 12; // under this an `includes` is a coin toss, so the row must START with the key

const asKey = (key: string): PromptKey => ({ key, strict: key.length < KEY_MIN });

/** What to look for, longest first: a row the REPL wrapped itself holds only the start of it. */
export function promptKeys(text: string): PromptKey[] {
  const first = (text.split("\n").map(normLine).find(Boolean) ?? "").slice(0, KEY_MAX);
  if (!first) return [];
  return first.length > KEY_SHORT ? [asKey(first), asKey(first.slice(0, KEY_SHORT))] : [asKey(first)];
}

export const lineHasPrompt = (line: string, k: PromptKey): boolean =>
  k.strict ? line.startsWith(k.key) : line.includes(k.key);

// How far a screen moved between two readings, in rows: 0 when nothing did (the top of the
// conversation, or a wheel the REPL ignored) and null when too little lines up to say — a
// rewritten screen, or a jump longer than the screen itself. Scrolling back moves content
// DOWN, so a hit is `after[i + shift] === before[i]`.
const ANCHORS = 4; // matching rows before a shift is a reading rather than a coincidence

export function screenShift(before: readonly string[], after: readonly string[]): number | null {
  let best = 0, bestAt: number | null = null;
  for (let d = 0; d < after.length; d++) {
    let n = 0;
    for (let i = 0; i + d < after.length && i < before.length; i++) {
      if (before[i].trim() && before[i] === after[i + d]) n++;
    }
    if (n > best) { best = n; bestAt = d; }
  }
  return best >= ANCHORS ? bestAt : null;
}

/**
 * Which end to page in from: the live end, unless this list starts where the conversation does
 * (a fresh pane always; a resumed one once the seed has restored what came before) — and then
 * the question's own clock, since rows pile up with time, not with questions (docs/sessions.md).
 */
export function huntFromTop(list: readonly Prompt[], p: Prompt, now: number, resumed: boolean): boolean {
  const start = list[0];
  if (resumed && !start?.restored) return false; // this list begins after the conversation did
  if (!p.at || !start?.at) return list.indexOf(p) < list.length / 2; // no clock to measure with
  return p.at - start.at < now - p.at;
}
